package Vistas;

import Distribuciones.discretas.Poisson;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sebastian
 */
public class PanelPoisson extends javax.swing.JPanel {

    /**
     * Creates new form PanelBinomial
     */
    public PanelPoisson() {
        initComponents();
        label_coma.setVisible(false);
        jFormattedTextField_x2.setVisible(false);
    }

    private void graficar() {
        Graficas migrafica = new Graficas(Graficas.AREA, "Distribución Poisson","X","P(x)");
       
              
        double lamda = Double.parseDouble(jFormattedTextField_n.getText().replace(",", "."));
        double[] x = rango(0, 50, 1);
        double[] y = new double[x.length];
        Poisson p = new Poisson(lamda);
        for (int i = 0; i < x.length; i++) {
            y[i] = p.funcionProbabilidad((int) x[i]);
        }

        migrafica.agregarSerieXY("x",x, y);
        JPanel panel = migrafica.obtienePanel();
        panel.setSize(jPanelGrafica.getSize());
        jPanelGrafica.removeAll();
        jPanelGrafica.add(panel,BorderLayout.CENTER);
        jPanelGrafica.revalidate();
        jPanelGrafica.repaint();

    }

    private double[] rango(double xi, double xn, double d) {
        int n = (int) ((xn - xi) / d);
        double[] r = new double[n+1];
        for (int i = 0; i <= n; i++) {
            r[i] = xi + d * i;
        }
        return r;
    }

    private boolean validarCampos() {
        boolean res = true;

        if (jFormattedTextField_n.getText().isEmpty()                
                || jFormattedTextField_x1.getText().isEmpty()) {
            return false;
        }
        if (jComboBoxVar.getSelectedIndex() == 3 && jFormattedTextField_x2.getText().isEmpty()) {
            return false;
        }
        try {
            
            double lamda = Double.parseDouble(jFormattedTextField_n.getText().replace(",", "."));
            int x1 = Integer.parseInt(jFormattedTextField_x1.getText());
            
            if (lamda <= 0) {
                JOptionPane.showMessageDialog(this, "n no puede tomar valores negativos ", "Error", JOptionPane.ERROR_MESSAGE);
                res = false;
            }
            if (x1 < 0 && x1 > Poisson.INFINITO) {
                JOptionPane.showMessageDialog(this, "x tiene que ser mayor a 0 ", "Error", JOptionPane.ERROR_MESSAGE);
                res = false;
            }
            if (jComboBoxVar.getSelectedIndex() == 3) {
                int x2 = Integer.parseInt(jFormattedTextField_x2.getText());
                if (x2 < 0 || x2 > Poisson.INFINITO) {
                    JOptionPane.showMessageDialog(this, "x tiene que ser mayor que 0 ", "Error", JOptionPane.ERROR_MESSAGE);
                    res = false;
                }
                if (x2 < x1) {
                    JOptionPane.showMessageDialog(this, "el segundo término debe ser mayor que el primero ", "Error", JOptionPane.ERROR_MESSAGE);
                    res = false;
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            res = false;
        }

        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        label_lamda = new javax.swing.JLabel();
        jFormattedTextField_n = new javax.swing.JFormattedTextField();
        jComboBoxVar = new javax.swing.JComboBox<>();
        jTextFieldResultado = new javax.swing.JTextField();
        jFormattedTextField_x1 = new javax.swing.JFormattedTextField();
        jFormattedTextField_x2 = new javax.swing.JFormattedTextField();
        label_X = new javax.swing.JLabel();
        label_coma = new javax.swing.JLabel();
        jButton_calcular = new javax.swing.JButton();
        label_X1 = new javax.swing.JLabel();
        LabelTitulo1 = new javax.swing.JLabel();
        jPanelGrafica = new javax.swing.JPanel();
        label_p1 = new javax.swing.JLabel();
        label_media = new javax.swing.JLabel();
        jTextFieldmedia = new javax.swing.JTextField();
        label_varianza = new javax.swing.JLabel();
        jTextFieldVarianza = new javax.swing.JTextField();
        jLabelLamda = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(720, 519));
        setLayout(null);

        LabelTitulo.setBackground(new java.awt.Color(51, 51, 51));
        LabelTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setText("Distribución Poisson");
        LabelTitulo.setToolTipText("");
        add(LabelTitulo);
        LabelTitulo.setBounds(214, 0, 261, 47);

        label_lamda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_lamda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lambda-32.png"))); // NOI18N
        label_lamda.setText(" =");
        add(label_lamda);
        label_lamda.setBounds(53, 90, 48, 32);

        jFormattedTextField_n.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_n.setToolTipText("valor del promedio (lambda)");
        jFormattedTextField_n.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jFormattedTextField_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_nActionPerformed(evt);
            }
        });
        add(jFormattedTextField_n);
        jFormattedTextField_n.setBounds(111, 95, 140, 23);

        jComboBoxVar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxVar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P(X=a)", "P(X<=a)", "P(X>a)", "P(a<=X<=b)" }));
        jComboBoxVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVarActionPerformed(evt);
            }
        });
        add(jComboBoxVar);
        jComboBoxVar.setBounds(53, 140, 105, 23);

        jTextFieldResultado.setEditable(false);
        add(jTextFieldResultado);
        jTextFieldResultado.setBounds(180, 130, 200, 40);

        jFormattedTextField_x1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField_x1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(jFormattedTextField_x1);
        jFormattedTextField_x1.setBounds(294, 95, 54, 23);

        jFormattedTextField_x2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField_x2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(jFormattedTextField_x2);
        jFormattedTextField_x2.setBounds(360, 95, 101, 23);

        label_X.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_X.setText("X =");
        add(label_X);
        label_X.setBounds(269, 98, 21, 17);

        label_coma.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_coma.setText(",");
        add(label_coma);
        label_coma.setBounds(352, 98, 4, 17);

        jButton_calcular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_calcular.setText("Calcular");
        jButton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcularActionPerformed(evt);
            }
        });
        add(jButton_calcular);
        jButton_calcular.setBounds(50, 180, 89, 25);

        label_X1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_X1.setText(":");
        add(label_X1);
        label_X1.setBounds(166, 143, 4, 17);

        LabelTitulo1.setBackground(new java.awt.Color(51, 51, 51));
        LabelTitulo1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo1.setText("X~P(");
        LabelTitulo1.setToolTipText("");
        add(LabelTitulo1);
        LabelTitulo1.setBounds(270, 50, 54, 29);

        javax.swing.GroupLayout jPanelGraficaLayout = new javax.swing.GroupLayout(jPanelGrafica);
        jPanelGrafica.setLayout(jPanelGraficaLayout);
        jPanelGraficaLayout.setHorizontalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelGraficaLayout.setVerticalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        add(jPanelGrafica);
        jPanelGrafica.setBounds(10, 244, 717, 275);

        label_p1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_p1.setText("Gráfica :");
        add(label_p1);
        label_p1.setBounds(53, 209, 58, 17);

        label_media.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_media.setText("Media =");
        add(label_media);
        label_media.setBounds(200, 190, 55, 17);

        jTextFieldmedia.setEditable(false);
        add(jTextFieldmedia);
        jTextFieldmedia.setBounds(269, 181, 100, 30);

        label_varianza.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_varianza.setText("Varianza =");
        add(label_varianza);
        label_varianza.setBounds(380, 190, 71, 17);

        jTextFieldVarianza.setEditable(false);
        add(jTextFieldVarianza);
        jTextFieldVarianza.setBounds(460, 180, 144, 30);

        jLabelLamda.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelLamda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lambda-32.png"))); // NOI18N
        jLabelLamda.setText(")");
        add(jLabelLamda);
        jLabelLamda.setBounds(330, 50, 50, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVarActionPerformed
        if (jComboBoxVar.getSelectedIndex() == 3) {
            label_coma.setVisible(true);
            jFormattedTextField_x2.setVisible(true);
        } else {
            label_coma.setVisible(false);
            jFormattedTextField_x2.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxVarActionPerformed

    private void jButton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcularActionPerformed
        if (validarCampos()) {
            
            double lamda = Double.parseDouble(jFormattedTextField_n.getText().replace(",", "."));
            Poisson p = new Poisson(lamda);
            int x1 = Integer.parseInt(jFormattedTextField_x1.getText());
            jTextFieldmedia.setText(String.format("%.3f", p.media()));
            jTextFieldVarianza.setText(String.format("%.3f", p.varianza()));
            switch (jComboBoxVar.getSelectedIndex()) {
                case 0:
                    jTextFieldResultado.setText(String.format("%.10f", p.funcionProbabilidad(x1)));
                    break;
                case 1:
                    jTextFieldResultado.setText(String.format("%.10f", p.funcionDistribucion(0, x1)));
                    break;
                case 2:
                    jTextFieldResultado.setText(String.format("%.10f", 1-p.funcionDistribucion(0, x1)));
                    break;
                case 3:
                    int x2 = Integer.parseInt(jFormattedTextField_x2.getText());
                    jTextFieldResultado.setText(String.format("%.10f", p.funcionDistribucion(x1, x2)));
                    break;
            }
            graficar();
        }
    }//GEN-LAST:event_jButton_calcularActionPerformed

    private void jFormattedTextField_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_nActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelTitulo1;
    private javax.swing.JButton jButton_calcular;
    private javax.swing.JComboBox<String> jComboBoxVar;
    private javax.swing.JFormattedTextField jFormattedTextField_n;
    private javax.swing.JFormattedTextField jFormattedTextField_x1;
    private javax.swing.JFormattedTextField jFormattedTextField_x2;
    private javax.swing.JLabel jLabelLamda;
    private javax.swing.JPanel jPanelGrafica;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldVarianza;
    private javax.swing.JTextField jTextFieldmedia;
    private javax.swing.JLabel label_X;
    private javax.swing.JLabel label_X1;
    private javax.swing.JLabel label_coma;
    private javax.swing.JLabel label_lamda;
    private javax.swing.JLabel label_media;
    private javax.swing.JLabel label_p1;
    private javax.swing.JLabel label_varianza;
    // End of variables declaration//GEN-END:variables
}
