/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author sebastian
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();        
        this.setIconImage (new ImageIcon(getClass().getResource("/imagenes/Calculator.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        menuDiscretas = new javax.swing.JMenu();
        itemUniformeD = new javax.swing.JMenuItem();
        itemBinomial = new javax.swing.JMenuItem();
        itemGeometrica = new javax.swing.JMenuItem();
        itemHiperGeometrica = new javax.swing.JMenuItem();
        itemPoisson = new javax.swing.JMenuItem();
        menuContinuas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de distribuciones");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        barraMenu.setBackground(new java.awt.Color(204, 204, 255));
        barraMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));
        barraMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barraMenu.setMargin(new java.awt.Insets(1, 1, 1, 1));
        barraMenu.setPreferredSize(new java.awt.Dimension(278, 30));

        menuDiscretas.setBackground(new java.awt.Color(102, 0, 255));
        menuDiscretas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        menuDiscretas.setText("Distribuciones discretas");
        menuDiscretas.setFocusPainted(true);
        menuDiscretas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuDiscretas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuDiscretas.setIconTextGap(5);

        itemUniformeD.setText("Uniforme");
        itemUniformeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUniformeDActionPerformed(evt);
            }
        });
        menuDiscretas.add(itemUniformeD);

        itemBinomial.setText("Binomial");
        itemBinomial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBinomialActionPerformed(evt);
            }
        });
        menuDiscretas.add(itemBinomial);

        itemGeometrica.setText("Geométrica");
        itemGeometrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGeometricaActionPerformed(evt);
            }
        });
        menuDiscretas.add(itemGeometrica);

        itemHiperGeometrica.setText("Hipergeométrica");
        itemHiperGeometrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHiperGeometricaActionPerformed(evt);
            }
        });
        menuDiscretas.add(itemHiperGeometrica);

        itemPoisson.setText("Poisson");
        itemPoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPoissonActionPerformed(evt);
            }
        });
        menuDiscretas.add(itemPoisson);

        barraMenu.add(menuDiscretas);

        menuContinuas.setBackground(new java.awt.Color(102, 102, 255));
        menuContinuas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        menuContinuas.setText("Distribuciones continuas");
        menuContinuas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        menuContinuas.setIconTextGap(20);
        barraMenu.add(menuContinuas);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGeometricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGeometricaActionPerformed
        PanelGeometrica pg = new PanelGeometrica();
        pg.setSize(panelPrincipal.getSize());       
        
        panelPrincipal.removeAll();
        panelPrincipal.add(pg,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_itemGeometricaActionPerformed

    private void itemBinomialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBinomialActionPerformed
        PanelBinomial pb = new PanelBinomial();
        pb.setSize(panelPrincipal.getSize());       
        
        panelPrincipal.removeAll();
        panelPrincipal.add(pb,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_itemBinomialActionPerformed

    private void itemUniformeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUniformeDActionPerformed
        PanelUniforme pu = new PanelUniforme();
        pu.setSize(panelPrincipal.getSize());       
        
        panelPrincipal.removeAll();
        panelPrincipal.add(pu,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_itemUniformeDActionPerformed

    private void itemPoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPoissonActionPerformed
        PanelPoisson pp = new PanelPoisson();
        pp.setSize(panelPrincipal.getSize());       
        
        panelPrincipal.removeAll();
        panelPrincipal.add(pp,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_itemPoissonActionPerformed

    private void itemHiperGeometricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHiperGeometricaActionPerformed
        PanelHipergeometrica ph = new PanelHipergeometrica();
        ph.setSize(panelPrincipal.getSize());       
        
        panelPrincipal.removeAll();
        panelPrincipal.add(ph,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_itemHiperGeometricaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemBinomial;
    private javax.swing.JMenuItem itemGeometrica;
    private javax.swing.JMenuItem itemHiperGeometrica;
    private javax.swing.JMenuItem itemPoisson;
    private javax.swing.JMenuItem itemUniformeD;
    private javax.swing.JMenu menuContinuas;
    private javax.swing.JMenu menuDiscretas;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
